### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in contains()

### ISSUE THREAD

**Issue by TracerMAK** [anthonykulis/cps215#3]
In a test I ran, if the bag is filled to its capacity and the user runs contains() with a search item that is not in the bag, the while loop in contains() runs its last iteration with an index that is out of bounds. I fixed mine by changing the order in the while loop.  I changed it to
while (index < _count && !item.equals(this._bag[index]) ) so the index check runs first. That way the loop is broken before equals() can run. Let me know if I'm not correct.

Here's a test I wrote:

```
// contains() fails if array is full and item not found
ArrayBag<Integer> newBag = new ArrayBag<Integer>(); 

// Fill bag to its default capacity
for (int x = 0; x < 25; x++) {
    newBag.add(x);
}

// Try to find the number 25 in the bag. Should return -1
newBag.contains(25);
```

**Comment by anthonykulis** [comment]
@TracerMAK  - haha! i totally missed that. great catch. i will update my solution. also, for some reason I didn't get emailed on this. make sure to tag me using the @ symbol. that will always go through. I think because i belong to some production repos I have general comments not mailing me, otherwise i will get like 50,000 a day. oh, but after I reply to your comment, I will then be automatically subscribed, so no need to keep tagging me.
